apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: patient-platform
resources:
  - ../../base
  - local-dependencies.yaml
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: HorizontalPodAutoscaler
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 2
  - target:
      kind: Secret
      name: auth-service-secret
    patch: |-
      - op: add
        path: /stringData
        value:
          DB_HOST: postgres
          DB_PASSWORD: secret
          JWT_SECRET: this-is-a-local-development-secret-with-more-than-32-characters
  - target:
      kind: Secret
      name: patient-service-secret
    patch: |-
      - op: add
        path: /stringData
        value:
          DB_HOST: postgres
          DB_PASSWORD: secret
  - target:
      kind: Secret
      name: audit-service-secret
    patch: |-
      - op: add
        path: /stringData
        value:
          DB_HOST: postgres
          DB_PASSWORD: secret
