apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: auth-service-secret
    creationPolicy: Merge
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: patient-management/application
        property: AUTH_DB_HOST
    - secretKey: DB_PASSWORD
      remoteRef:
        key: patient-management/application
        property: AUTH_DB_PASSWORD
    - secretKey: JWT_SECRET
      remoteRef:
        key: patient-management/application
        property: JWT_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: patient-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: patient-service-secret
    creationPolicy: Merge
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: patient-management/application
        property: PATIENT_DB_HOST
    - secretKey: DB_PASSWORD
      remoteRef:
        key: patient-management/application
        property: PATIENT_DB_PASSWORD
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audit-service
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: audit-service-secret
    creationPolicy: Merge
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: patient-management/application
        property: AUDIT_DB_HOST
    - secretKey: DB_PASSWORD
      remoteRef:
        key: patient-management/application
        property: AUDIT_DB_PASSWORD
