apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: patient-platform
resources:
  - ../../base
  - external-secrets.yaml
images:
  - name: api-gateway
    newName: AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/api-gateway
    newTag: 1.0.0
  - name: auth-service
    newName: AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/auth-service
    newTag: 1.0.0
  - name: patient-service
    newName: AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/patient-service
    newTag: 1.0.0
  - name: billing-service
    newName: AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/billing-service
    newTag: 1.0.0
  - name: audit-service
    newName: AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/audit-service
    newTag: 1.0.0
  - name: notification-service
    newName: AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/notification-service
    newTag: 1.0.0
patches:
  - target:
      kind: ConfigMap
      name: patient-service-config
    patch: |-
      - op: replace
        path: /data/KAFKA_BOOTSTRAP_SERVERS
        value: REPLACE_WITH_MSK_BOOTSTRAP_BROKERS
  - target:
      kind: ConfigMap
      name: audit-service-config
    patch: |-
      - op: replace
        path: /data/KAFKA_BOOTSTRAP_SERVERS
        value: REPLACE_WITH_MSK_BOOTSTRAP_BROKERS
  - target:
      kind: ConfigMap
      name: notification-service-config
    patch: |-
      - op: replace
        path: /data/KAFKA_BOOTSTRAP_SERVERS
        value: REPLACE_WITH_MSK_BOOTSTRAP_BROKERS
  - target:
      kind: Ingress
      name: patient-platform
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: REPLACE_WITH_INGRESS_HOST
