services:
  localstack:
    image: localstack/localstack:latest
    container_name: patient-management-localstack
    ports:
      - "4566:4566"
    environment:
      DEBUG: ${LOCALSTACK_DEBUG:-0}
      LOCALSTACK_AUTH_TOKEN: ${LOCALSTACK_AUTH_TOKEN:-}
      EKS_K8S_PROVIDER: k3s
      PERSISTENCE: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - localstack-data:/var/lib/localstack

volumes:
  localstack-data:
