import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { ArrowLeft, Plus, Save, Trash2 } from 'lucide-react'
import { useFieldArray, useForm } from 'react-hook-form'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { z } from 'zod'
import { billingApi } from '../../api/billingApi'
import { ApiRequestError } from '../../api/httpClient'
import { patientApi } from '../../api/patientApi'
import { PageHeader } from '../../components/layout/PageHeader'

const schema = z.object({ patientId: z.number().int().positive('Select a patient'), appointmentId: z.number().int().nonnegative().optional(), dueDate: z.string().min(1, 'Due date is required'), status: z.enum(['DRAFT', 'ISSUED']), items: z.array(z.object({ description: z.string().trim().min(2, 'Description is required'), quantity: z.number().int().min(1), unitPrice: z.number().min(0) })).min(1) })
type Values = z.infer<typeof schema>
export function InvoiceFormPage() {
  const navigate = useNavigate(); const client = useQueryClient()
  const [searchParams] = useSearchParams()
  const patients = useQuery({ queryKey: ['patients', 'billing-picker'], queryFn: () => patientApi.list({ page: 0, size: 100, active: true }) })
  const nextWeek = new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10)
  const { register, control, handleSubmit, setError, formState: { errors } } = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { patientId: Number(searchParams.get('patientId')) || 0, appointmentId: undefined, dueDate: nextWeek, status: 'ISSUED', items: [{ description: '', quantity: 1, unitPrice: 0 }] } })
  const fields = useFieldArray({ control, name: 'items' })
  const mutation = useMutation({ mutationFn: async (values: Values) => {
    const patient = patients.data?.patients.find((item) => item.id === values.patientId)
    if (!patient) throw new Error('Select a patient')
    let accountId: string
    try { accountId = (await billingApi.patient(patient.id)).account.id }
    catch (error) { if (error instanceof ApiRequestError && error.status === 404) accountId = (await billingApi.createAccount(patient)).accountId; else throw error }
    return billingApi.createInvoice({ billingAccountId: accountId, appointmentId: values.appointmentId || undefined, dueDate: values.dueDate, status: values.status, items: values.items })
  }, onSuccess: (invoice) => { client.invalidateQueries({ queryKey: ['billing-invoices'] }); client.invalidateQueries({ queryKey: ['billing-statistics'] }); navigate(`/billing/invoices/${invoice.id}`) }, onError: (error) => { if (error instanceof ApiRequestError) Object.entries(error.fieldErrors).forEach(([field, message]) => { if (field === 'dueDate' || field === 'billingAccountId') setError(field === 'billingAccountId' ? 'patientId' : field, { message }) }); setError('root', { message: error instanceof Error ? error.message : 'Invoice could not be created.' }) } })
  const input = 'mt-2 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm outline-none focus:border-sky-500 focus:ring-4 focus:ring-sky-100'
  return <div className="mx-auto max-w-5xl space-y-7"><PageHeader eyebrow="New billing record" title="Create invoice" description="Add billable items; HealthFlow calculates every subtotal and the final amount." actions={<Link to="/billing/invoices" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold"><ArrowLeft className="h-4 w-4" /> Cancel</Link>} />
    <form onSubmit={handleSubmit((values) => mutation.mutate(values))} className="space-y-6" noValidate><section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><h2 className="font-bold">Invoice information</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><div><label className="text-sm font-semibold" htmlFor="patientId">Patient</label><select id="patientId" className={input} {...register('patientId', { valueAsNumber: true })}><option value={0}>Select a patient</option>{patients.data?.patients.map((patient) => <option key={patient.id} value={patient.id}>{patient.name} · HF-{String(patient.id).padStart(5, '0')}</option>)}</select>{errors.patientId && <p className="mt-1 text-xs text-rose-600">{errors.patientId.message}</p>}</div><div><label className="text-sm font-semibold" htmlFor="appointmentId">Appointment ID <span className="font-normal text-slate-400">(optional)</span></label><input id="appointmentId" type="number" min="1" className={input} {...register('appointmentId', { setValueAs: (value) => value === '' ? undefined : Number(value) })} /></div><div><label className="text-sm font-semibold" htmlFor="dueDate">Due date</label><input id="dueDate" type="date" className={input} {...register('dueDate')} />{errors.dueDate && <p className="mt-1 text-xs text-rose-600">{errors.dueDate.message}</p>}</div><div><label className="text-sm font-semibold" htmlFor="status">Initial status</label><select id="status" className={input} {...register('status')}><option value="ISSUED">Issued — ready for payment</option><option value="DRAFT">Draft — not payable</option></select></div></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div className="flex items-center justify-between"><div><h2 className="font-bold">Invoice items</h2><p className="mt-1 text-xs text-slate-500">Totals are verified again by the Billing Service.</p></div><button type="button" onClick={() => fields.append({ description: '', quantity: 1, unitPrice: 0 })} className="inline-flex items-center gap-2 rounded-xl border border-sky-200 px-3 py-2 text-sm font-bold text-sky-700"><Plus className="h-4 w-4" /> Add item</button></div><div className="mt-5 space-y-4">{fields.fields.map((field, index) => <div key={field.id} className="grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-[1fr_100px_150px_auto] sm:items-end"><div><label className="text-xs font-bold text-slate-500">Description</label><input className={input} placeholder="Consultation or procedure" {...register(`items.${index}.description`)} />{errors.items?.[index]?.description && <p className="mt-1 text-xs text-rose-600">{errors.items[index].description.message}</p>}</div><div><label className="text-xs font-bold text-slate-500">Quantity</label><input type="number" min="1" className={input} {...register(`items.${index}.quantity`, { valueAsNumber: true })} /></div><div><label className="text-xs font-bold text-slate-500">Unit price</label><input type="number" min="0" step="0.01" className={input} {...register(`items.${index}.unitPrice`, { valueAsNumber: true })} /></div><button type="button" disabled={fields.fields.length === 1} onClick={() => fields.remove(index)} className="mb-1 rounded-xl p-3 text-rose-600 hover:bg-rose-50 disabled:opacity-30" aria-label="Remove item"><Trash2 className="h-4 w-4" /></button></div>)}</div></section>
    {errors.root && <div className="rounded-xl bg-rose-50 p-4 text-sm text-rose-700" role="alert">{errors.root.message}</div>}<div className="flex justify-end"><button disabled={mutation.isPending} className="inline-flex min-w-44 items-center justify-center gap-2 rounded-xl bg-sky-600 px-5 py-3 text-sm font-bold text-white disabled:opacity-60"><Save className="h-4 w-4" /> {mutation.isPending ? 'Creating…' : 'Create invoice'}</button></div></form>
  </div>
}
