import { useQuery } from '@tanstack/react-query'
import { ArrowLeft, Banknote, CalendarDays, UserRound } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { billingApi } from '../../api/billingApi'
import { ErrorState } from '../../components/feedback/ErrorState'
import { LoadingState } from '../../components/feedback/LoadingState'
import { PageHeader } from '../../components/layout/PageHeader'
import { formatCurrency, formatDate, formatDateTime, titleCase } from '../../utils/format'
import { BillingStatusBadge } from './BillingStatusBadge'

export function InvoiceDetailsPage() {
  const { id } = useParams(); const query = useQuery({ queryKey: ['billing-invoice', id], queryFn: () => billingApi.invoice(id!) })
  if (query.isLoading) return <LoadingState label="Opening invoice" />
  if (query.isError || !query.data) return <ErrorState message={query.error?.message ?? 'Invoice not found'} onRetry={() => query.refetch()} />
  const invoice = query.data; const payable = ['ISSUED', 'PARTIALLY_PAID', 'OVERDUE'].includes(invoice.status)
  return <div className="mx-auto max-w-6xl space-y-7"><PageHeader eyebrow="Invoice details" title={invoice.invoiceNumber} description={`Created ${formatDateTime(invoice.createdAt)}`} actions={<><Link to="/billing/invoices" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold text-slate-700"><ArrowLeft className="h-4 w-4" /> Invoices</Link>{payable && <Link to={`/billing/invoices/${id}/payment`} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-emerald-700"><Banknote className="h-4 w-4" /> Record payment</Link>}</>} />
    <div className="grid gap-6 lg:grid-cols-[1.35fr_.65fr]"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 className="font-bold">Invoice items</h2><BillingStatusBadge status={invoice.status} /></div><div className="overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">Description</th><th className="px-5 py-3">Quantity</th><th className="px-5 py-3">Unit price</th><th className="px-5 py-3 text-right">Subtotal</th></tr></thead><tbody className="divide-y divide-slate-100">{invoice.items.map((item) => <tr key={item.id}><td className="px-5 py-4 text-sm font-semibold">{item.description}</td><td className="px-5 py-4 text-sm text-slate-600">{item.quantity}</td><td className="px-5 py-4 text-sm text-slate-600">{formatCurrency(item.unitPrice)}</td><td className="px-5 py-4 text-right text-sm font-bold">{formatCurrency(item.subtotal)}</td></tr>)}</tbody></table></div><dl className="ml-auto w-full max-w-sm space-y-2 border-t border-slate-100 p-5 text-sm"><div className="flex justify-between"><dt className="text-slate-500">Invoice total</dt><dd className="font-semibold">{formatCurrency(invoice.totalAmount)}</dd></div><div className="flex justify-between"><dt className="text-slate-500">Payments</dt><dd className="font-semibold text-emerald-700">− {formatCurrency(invoice.paidAmount)}</dd></div><div className="flex justify-between border-t border-slate-100 pt-3 text-base"><dt className="font-bold">Balance due</dt><dd className="font-bold">{formatCurrency(invoice.balance)}</dd></div></dl></section>
      <aside className="space-y-5"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Billing information</h2><dl className="mt-5 space-y-4"><div><dt className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-400"><UserRound className="h-4 w-4" /> Patient</dt><dd className="mt-2"><Link to={`/billing/accounts/patient/${invoice.patientId}`} className="text-sm font-bold text-sky-700">Patient HF-{String(invoice.patientId).padStart(5, '0')}</Link></dd></div><div><dt className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-slate-400"><CalendarDays className="h-4 w-4" /> Due date</dt><dd className="mt-2 text-sm font-semibold">{formatDate(invoice.dueDate)}</dd></div>{invoice.appointmentId && <div><dt className="text-xs font-bold uppercase tracking-wider text-slate-400">Appointment</dt><dd className="mt-2"><Link to={`/appointments/${invoice.appointmentId}`} className="text-sm font-bold text-sky-700">Appointment #{invoice.appointmentId}</Link></dd></div>}</dl></section>
      <section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-bold">Payment history</h2><div className="mt-4 space-y-3">{invoice.payments.length ? invoice.payments.map((payment) => <div key={payment.id} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between"><span className="text-sm font-bold text-emerald-700">{formatCurrency(payment.amount)}</span><span className="text-xs font-semibold text-slate-500">{titleCase(payment.paymentMethod)}</span></div><p className="mt-1 text-xs text-slate-500">{formatDateTime(payment.paidAt)}{payment.reference ? ` · ${payment.reference}` : ''}</p></div>) : <p className="text-sm text-slate-500">No payments recorded.</p>}</div></section></aside></div>
  </div>
}
