POST http://localhost:8080/api/patients
Content-Type: application/json
Accept: application/json

{
  "name": "audit test notification 2 ",
  "email": "john@test5.com",
  "address": "Colombo",
  "dateOfBirth": "2000-01-01"
}