POST http://localhost:8080/api/patients
Content-Type: application/json
Accept: application/json

{
  "name": "Kafka test patient",
  "email": "john@test2.com",
  "address": "Colombo",
  "dateOfBirth": "2000-01-01"
}