apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: patient-platform
resources:
  - namespace.yaml
  - api-gateway.yaml
  - auth-service.yaml
  - patient-service.yaml
  - billing-service.yaml
  - audit-service.yaml
  - notification-service.yaml
  - hpa.yaml
  - ingress.yaml
